### ISSUE TITLE
Add comments to the source code! :heart: 

### ISSUE THREAD

**Issue by Zigolox** [simonthor/whitespace.py#1]
Since the code is using quite dense and complex expressions i feel some comments could be necessary for an run-of-the-mill python programmer (like myself) to understand the code to it's fullest! ;)

**Comment by simonthor** [comment]
That is a good point. Will fix that 👍

**Comment by simonthor** [comment]
Fixed it here: 2b299c553f8265944904190ee6b5d2a65b49276c
